# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Tour
  #   url: tour
  #   weight: 10
  # - name: Tutorials
  #   url: tutorials
  #   weight: 20
  # - name: Home
  #   url: home_
    # weight: 20
  - name: People
    url: people
    weight: 30
  - name: Gallery
    url: gallery
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  # - name: Web Servers
  #   url: web_server
  #   weight: 60
  - name: News
    url: news
    weight: 70
  - name: Tutorial
    url: link
    weight: 80
  - name: Contact
    url: contact
    weight: 90
